version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: /api
      FEATURE_REGISTER: ${FEATURE_REGISTER:-off}
      FEATURE_PASSWORD_RESET: ${FEATURE_PASSWORD_RESET:-off}
      NEXT_PUBLIC_FEATURE_REGISTER: ${NEXT_PUBLIC_FEATURE_REGISTER:-${FEATURE_REGISTER:-off}}
      NEXT_PUBLIC_FEATURE_PASSWORD_RESET: ${NEXT_PUBLIC_FEATURE_PASSWORD_RESET:-${FEATURE_PASSWORD_RESET:-off}}
    expose:
      - '3000'
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE:-backend:latest}
    expose:
      - '8000'

  proxy:
    image: nginx:1.27-alpine
    ports:
      - '80:80'
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
